# Generated by Django 6.1 on 2026-08-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('brokerages', '0002_initial_groups'),
        ('clients', '0001_initial'),
        ('insurers', '0001_initial'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('policy_number', models.CharField(max_length=80, verbose_name='número da apólice')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='início de vigência')),
                ('end_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='fim de vigência')),
                ('premium_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='prêmio')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('expired', 'Vencida'), ('cancelled', 'Cancelada'), ('pending', 'Pendente')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('ai_summary', models.TextField(blank=True, verbose_name='resumo IA')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='branches.insurancebranch', verbose_name='ramo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='clients.client', verbose_name='cliente')),
                ('insurance_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurers.insurancecompany', verbose_name='seguradora')),
                ('proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy', to='proposals.proposal', verbose_name='proposta')),
            ],
            options={
                'verbose_name': 'apólice',
                'verbose_name_plural': 'apólices',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['brokerage', 'status'], name='policies_po_brokera_e7462b_idx'), models.Index(fields=['brokerage', 'end_date'], name='policies_po_brokera_a7b13d_idx')],
                'constraints': [models.UniqueConstraint(fields=('brokerage', 'insurance_company', 'policy_number'), name='unique_policy_number_per_brokerage_insurer')],
            },
        ),
    ]
