# Generated by Django 6.1 on 2026-08-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0002_initial_groups'),
        ('clients', '0001_initial'),
        ('covered_items', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('claim_number', models.CharField(max_length=80, verbose_name='número do sinistro')),
                ('status', models.CharField(choices=[('reported', 'Avisado'), ('under_review', 'Em análise'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('paid', 'Pago'), ('closed', 'Encerrado')], db_index=True, default='reported', max_length=20, verbose_name='status')),
                ('occurred_at', models.DateField(blank=True, null=True, verbose_name='data da ocorrência')),
                ('description', models.TextField(verbose_name='descrição')),
                ('ai_summary', models.TextField(blank=True, verbose_name='resumo IA')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='clients.client', verbose_name='cliente')),
                ('covered_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='covered_items.covereditem', verbose_name='item coberto')),
            ],
            options={
                'verbose_name': 'sinistro',
                'verbose_name_plural': 'sinistros',
                'ordering': ('-created_at',),
            },
        ),
    ]
