# Generated by Django 6.1 on 2026-08-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='policies.policy', verbose_name='apólice'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['brokerage', 'status'], name='claims_clai_brokera_25009b_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['brokerage', 'occurred_at'], name='claims_clai_brokera_00838e_idx'),
        ),
    ]
