# Generated by Django 6.1 on 2026-08-24 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0002_initial_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('document', models.CharField(blank=True, max_length=32, verbose_name='documento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefone')),
                ('type', models.CharField(choices=[('individual', 'Pessoa física'), ('company', 'Pessoa jurídica')], default='individual', max_length=20, verbose_name='tipo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('ai_summary', models.TextField(blank=True, verbose_name='resumo IA')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['brokerage', 'name'], name='clients_cli_brokera_704036_idx'), models.Index(fields=['brokerage', 'created_at'], name='clients_cli_brokera_24ed55_idx')],
            },
        ),
    ]
