# Generated by Django 6.1 on 2026-08-24 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0002_initial_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'ramo de seguro',
                'verbose_name_plural': 'ramos de seguro',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['brokerage', 'name'], name='branches_in_brokera_23b472_idx')],
            },
        ),
    ]
