# Generated by Django 6.1 on 2026-08-24 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0002_initial_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('policy_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID da apólice')),
                ('item_type', models.CharField(choices=[('vehicle', 'Veículo'), ('property', 'Imóvel'), ('life', 'Vida'), ('travel', 'Viagem'), ('business', 'Empresarial'), ('other', 'Outro')], default='other', max_length=20, verbose_name='tipo')),
                ('description', models.TextField(verbose_name='descrição')),
                ('insured_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor segurado')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'item coberto',
                'verbose_name_plural': 'itens cobertos',
                'ordering': ('-created_at',),
            },
        ),
    ]
