# Generated by Django 6.1 on 2026-08-24 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('covered_items', '0001_initial'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covereditem',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covered_items', to='proposals.proposal', verbose_name='proposta'),
        ),
        migrations.AddIndex(
            model_name='covereditem',
            index=models.Index(fields=['brokerage', 'item_type'], name='covered_ite_brokera_def811_idx'),
        ),
        migrations.AddIndex(
            model_name='covereditem',
            index=models.Index(fields=['brokerage', 'created_at'], name='covered_ite_brokera_dc8374_idx'),
        ),
    ]
