# Generated by Django 6.1 on 2026-08-24 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('brokerages', '0002_initial_groups'),
        ('clients', '0001_initial'),
        ('insurers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('converted', 'Convertida'), ('expired', 'Expirada')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('premium_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='prêmio')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='percentual de comissão')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válida até')),
                ('ai_summary', models.TextField(blank=True, verbose_name='resumo IA')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='branches.insurancebranch', verbose_name='ramo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='clients.client', verbose_name='cliente')),
                ('insurance_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='insurers.insurancecompany', verbose_name='seguradora')),
            ],
            options={
                'verbose_name': 'proposta',
                'verbose_name_plural': 'propostas',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('policy_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID da apólice')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('limit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='limite')),
                ('deductible_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='franquia')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='proposals.proposal', verbose_name='proposta')),
            ],
            options={
                'verbose_name': 'cobertura',
                'verbose_name_plural': 'coberturas',
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['brokerage', 'status'], name='proposals_p_brokera_ce51de_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['brokerage', 'created_at'], name='proposals_p_brokera_91c62c_idx'),
        ),
        migrations.AddIndex(
            model_name='coverage',
            index=models.Index(fields=['brokerage', 'name'], name='proposals_c_brokera_aed1c7_idx'),
        ),
    ]
