# Generated by Django 6.1 on 2026-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('task_name', models.CharField(max_length=200, verbose_name='task')),
                ('task_id', models.CharField(blank=True, max_length=120, verbose_name='ID da task')),
                ('brokerage_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID da corretora')),
                ('user_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID do usuário')),
                ('status', models.CharField(choices=[('started', 'Iniciada'), ('success', 'Concluída'), ('failure', 'Falhou')], db_index=True, default='started', max_length=20, verbose_name='status')),
                ('message', models.TextField(blank=True, verbose_name='mensagem')),
            ],
            options={
                'verbose_name': 'evento Celery',
                'verbose_name_plural': 'eventos Celery',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='dj_celery_p_status_96a6c2_idx')],
            },
        ),
    ]
