# Generated by Django 6.1 on 2026-08-24 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0002_initial_groups'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('color', models.CharField(default='#1947e5', max_length=20, verbose_name='cor')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posição')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'etapa do CRM',
                'verbose_name_plural': 'etapas do CRM',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor estimado')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('won', 'Ganha'), ('lost', 'Perdida'), ('archived', 'Arquivada')], db_index=True, default='open', max_length=20, verbose_name='status')),
                ('ai_summary', models.TextField(blank=True, verbose_name='resumo IA')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='clients.client', verbose_name='cliente')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.dealstage', verbose_name='etapa')),
            ],
            options={
                'verbose_name': 'negociação',
                'verbose_name_plural': 'negociações',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='dealstage',
            index=models.Index(fields=['brokerage', 'position'], name='crm_dealsta_brokera_7821ba_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['brokerage', 'status'], name='crm_deal_brokera_2b3cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['brokerage', 'assigned_to'], name='crm_deal_brokera_37da12_idx'),
        ),
    ]
