# Generated by Django 6.1 on 2026-08-24 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0002_initial_groups'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('endorsement_number', models.CharField(max_length=80, verbose_name='número do endosso')),
                ('type', models.CharField(choices=[('change', 'Alteração'), ('cancellation', 'Cancelamento'), ('addition', 'Inclusão'), ('correction', 'Correção')], default='change', max_length=20, verbose_name='tipo')),
                ('description', models.TextField(verbose_name='descrição')),
                ('effective_date', models.DateField(verbose_name='data de vigência')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='policies.policy', verbose_name='apólice')),
            ],
            options={
                'verbose_name': 'endosso',
                'verbose_name_plural': 'endossos',
                'ordering': ('-effective_date', '-created_at'),
                'indexes': [models.Index(fields=['brokerage', 'effective_date'], name='endorsement_brokera_5ea558_idx')],
                'constraints': [models.UniqueConstraint(fields=('brokerage', 'policy', 'endorsement_number'), name='unique_endorsement_per_policy')],
            },
        ),
    ]
