# Generated by Django 6.1 on 2026-08-24 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0002_initial_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(default='Nova conversa', max_length=180, verbose_name='título')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'sessão de chat IA',
                'verbose_name_plural': 'sessões de chat IA',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente')], max_length=20, verbose_name='papel')),
                ('content_markdown', models.TextField(verbose_name='conteúdo em Markdown')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_agents.aichatsession', verbose_name='sessão')),
            ],
            options={
                'verbose_name': 'mensagem de chat IA',
                'verbose_name_plural': 'mensagens de chat IA',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='aichatsession',
            index=models.Index(fields=['brokerage', 'user', 'updated_at'], name='ai_agents_a_brokera_4dce21_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['brokerage', 'session', 'created_at'], name='ai_agents_a_brokera_50952a_idx'),
        ),
    ]
