# Generated by Django 6.1 on 2026-08-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0002_initial_groups'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('due_date', models.DateField(db_index=True, verbose_name='vencimento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('renewed', 'Renovada'), ('lost', 'Perdida'), ('expired', 'Expirada')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='policies.policy', verbose_name='apólice')),
            ],
            options={
                'verbose_name': 'renovação',
                'verbose_name_plural': 'renovações',
                'ordering': ('due_date',),
                'indexes': [models.Index(fields=['brokerage', 'due_date'], name='renewals_re_brokera_f6fbe9_idx'), models.Index(fields=['brokerage', 'status'], name='renewals_re_brokera_238c53_idx')],
            },
        ),
    ]
