# Generated by Django 6.1 on 2026-08-24 10:45

import attachments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0002_initial_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('file', models.FileField(upload_to=attachments.models.private_upload_to, verbose_name='arquivo')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='nome original')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='tipo de conteúdo')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='tamanho em bytes')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'anexo',
                'verbose_name_plural': 'anexos',
                'ordering': ('-created_at',),
            },
        ),
    ]
