# Generated by Django 6.1 on 2026-08-24 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0002_initial'),
        ('policies', '0001_initial'),
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='policies.policy', verbose_name='apólice'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='proposals.proposal', verbose_name='proposta'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='enviado por'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['brokerage', 'created_at'], name='attachments_brokera_4e6c60_idx'),
        ),
    ]
