# Generated by Django 6.1 on 2026-08-24 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0002_initial_groups'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('document', models.CharField(blank=True, max_length=32, verbose_name='documento')),
                ('type', models.CharField(choices=[('person', 'Pessoa física'), ('company', 'Empresa')], default='person', max_length=20, verbose_name='tipo')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='percentual de comissão')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'agente',
                'verbose_name_plural': 'agentes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('document', models.CharField(blank=True, max_length=32, verbose_name='documento')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='percentual de comissão')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producers', to='commissions.agent', verbose_name='agente')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'produtor',
                'verbose_name_plural': 'produtores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='comissão bruta')),
                ('brokerage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor da corretora')),
                ('agent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor do agente')),
                ('producer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor do produtor')),
                ('status', models.CharField(choices=[('expected', 'Prevista'), ('received', 'Recebida'), ('partially_paid', 'Parcialmente paga'), ('paid', 'Paga'), ('cancelled', 'Cancelada')], db_index=True, default='expected', max_length=20, verbose_name='status')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commissions.agent', verbose_name='agente')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='policies.policy', verbose_name='apólice')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commissions.producer', verbose_name='produtor')),
            ],
            options={
                'verbose_name': 'comissão',
                'verbose_name_plural': 'comissões',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['brokerage', 'name'], name='commissions_brokera_10ad64_idx'),
        ),
        migrations.AddIndex(
            model_name='producer',
            index=models.Index(fields=['brokerage', 'name'], name='commissions_brokera_aadeae_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['brokerage', 'status'], name='commissions_brokera_fc6275_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['brokerage', 'created_at'], name='commissions_brokera_ec0276_idx'),
        ),
    ]
