# Generated by Django 6.1 on 2026-08-24 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0002_initial_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('level', models.CharField(choices=[('info', 'Informação'), ('success', 'Sucesso'), ('warning', 'Atenção'), ('error', 'Erro')], default='info', max_length=20, verbose_name='nível')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='lida')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='brokerages.brokerage', verbose_name='corretora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['brokerage', 'user', 'is_read'], name='notificatio_brokera_2ae560_idx')],
            },
        ),
    ]
